INSERT INTO genres (genre_name) VALUES
('Fantasy'),
('Science Fiction'),
('Mystery'),
('Thriller'),
('Romance'),
('Horror'),
('Historical Fiction'),
('Adventure'),
('Young Adult'),
('Children'),
('Biography'),
('Autobiography'),
('History'),
('Politics'),
('Philosophy'),
('Religion'),
('Psychology'),
('Self-Help'),
('Business'),
('Economics'),
('Education'),
('Science'),
('Technology'),
('Programming'),
('Art'),
('Music'),
('Poetry'),
('Drama'),
('Comics'),
('Graphic Novel'),
('Travel'),
('Cooking'),
('Health'),
('Sports'),
('True Crime'),
('Law')
ON DUPLICATE KEY UPDATE genre_name = genre_name;